- name: setup local development environment
  hosts: all
  become: yes
  roles:
    - common
    - mariadb
    - apache
    - php
    - mailcatcher
  tasks:
    - name: restart service
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd
        - mariadb
