- name: setup local development environment
  hosts: all
  become: yes
  roles:
    - common
    - mariadb
    - lexicon
    - dehydrated
    - apache
    - php
    - mailcatcher
    - wp-cli
    - phpmyadmin
    - wwwsqldesigner
    - rtail
  tasks:
    - name: restart service
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd
        - mariadb
