---
- name: install package
  yum:
    name: supervisor
    enablerepo: epel
- name: create supervisor setting files
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf
- name: create program setting file
  template:
    src: program.ini.j2
    dest: /etc/supervisord.d/program.ini
- name: create eventlistener setting file
  template:
    src: eventlistener.ini.j2
    dest: /etc/supervisord.d/eventlistener.ini
- name: create group setting file
  template:
    src: group.ini.j2
    dest: /etc/supervisord.d/group.ini
- name: supervisor is active and enabled on system startup
  systemd:
    name: supervisord
    state: started
    enabled: yes
