# --------------
# ドメイン名
# ※以下の各設定項目に記載している「{{ domain }}」の値
# --------------
domain: example.com

# --------------
# MariaDBのrootパスワード
# --------------
mariadb_root_password: r00tP@55w0rd

# --------------
# PHPのバージョン
#
# 指定可能な値は以下の通り
# - 5.4
# - 5.5
# - 5.6
# - 7.0
# - 7.1
# - 7.2
# --------------
php_version: 7.1

# --------------
# MariaDBの設定
# --------------
# デフォルトの文字コード
mariadb_default_charset: utf8mb4
# デフォルトの文字照合順序
mariadb_default_collation: utf8mb4_general_ci

# --------------
# データベース
# --------------
mariadb_databases:
  # 開発用データベース
  - name: app_dev
    password: app_dev_p@ssw0rd
    hosts:
      - "127.0.0.1"
      - localhost
  # テスト用データベース
  - name: app_test
    import_data: /vagrant/source/test_data.sql
    password: app_test_p@ssw0rd
    hosts:
      - "127.0.0.1"
      - localhost
  # ステージング用データベース
  - name: app_staging
    password: app_staging_p@ssw0rd
    hosts:
      - "127.0.0.1"
      - localhost
  # 本番用データベース
  - name: app_prod
    user: app_prod_user
    password: app_prod_p@55w0rd
    hosts:
      - "127.0.0.1"
      - localhost
  # WWW SQL Designer用データベース
  - name: wwwsqldesigner
    password: wwwsqldesigner_p@ssw0rd
    hosts:
      - "127.0.0.1"
      - localhost

# --------------
# インストールするPHPのパッケージ
# --------------
php_packages:
  - php
  - php-common
  - php-cli
  - php-devel
  - php-opcache
  - php-mbstring
  - php-mysqlnd
  - php-intl
  - php-json
  - php-pdo
  - php-gd
  - php-xml

# --------------
# php.iniの初期値を上書きする項目
# その他の設定値は、「provision/roles/php/defaults/main.yml」の「php_cfg」の項目を参照
# --------------
php_cfg:
  sendmail_path: "/usr/bin/env catchmail -f admin@{{ domain }}"

# --------------
# Apacheのバーチャルホストの設定
# --------------
apache_vhosts:
  # ローカルのPCと共有している領域 ( http://www.<ドメイン>/ )
  - name: 00-default
    server_name: www.{{ domain }}                         # サーバー名
    document_root: /vagrant/source                        # ドキュメントルート
    server_alias: "{{ domain }}"                          # サーバー名の別名
  # phpMyAdmin用のバーチャルホスト ( http://db.<ドメイン>/ )
  - name: 01-phpMyAdmin
    server_name: db.{{ domain }}
    document_root: "{{ phpmyadmin_dest }}"
    options:                                              # Optionsの設定値
      - "-Indexes"
      - "+FollowSymLinks"
    allow_override: All                                   # AllowOverrideの設定値
    require:                                              # Requireの設定値
      - type: ip
        value: 192.168.33
  # MailCatcher用のバーチャルホスト ( http://mail.<ドメイン>/ )
  - name: 02-MailCatcher
    server_name: mail.{{ domain }}
    # リバースプロキシの設定
    proxy_pass:
      - from: /
        to: "http://localhost:{{ mailcatcher_web_port }}/"
    proxy_pass_reverse:
      - from: /
        to: "http://localhost:{{ mailcatcher_web_port }}/"
  # rtail用のバーチャルホスト ( http://log.<ドメイン>/ )
  # - name: 03-rtail
  #   server_name: log.{{ domain }}
  #   # リバースプロキシの設定
  #   proxy_pass:
  #     - from: /
  #       to: "http://localhost:8888/"
  #   proxy_pass_reverse:
  #     - from: /
  #       to: "http://localhost:8888/"

# --------------
# Apacheの設定
# その他の設定値は、「provision/roles/apache/defaults/main.yml」を参照
# --------------
apache_cfg:
  # EnableSendfileをOffに変更(VirtualBoxの共有ディレクトリ機能用)
  enable_sendfile: no

# 不要なモジュールを無効化
apache_module_lua: no
apache_module_dav:
  dav: no
  dav_fs: no
  dav_lock: no
apache_module_lbmethod:
  bybusyness: no
  byrequests: no
  bytraffic: no
  heartbeat: no
apache_module_proxy:
  ajp: no
  balancer: no
  ftp: no
