domain: example.com

# mariadb_root_password: root_passW00rd

php_version: 7.0

php_packages:
  - php
  - php-common
  - php-cli
  - php-devel
  - php-opcache
  - php-mbstring
  - php-mysqlnd
  - php-json
  - php-pdo
  - php-gd
  - php-xml

php_cfg:
  sendmail_path: "/usr/bin/env catchmail -f admin@{{ domain }}"

apache_vhosts:
  - name: 00-default
    server_name: www.{{ domain }}
    document_root: /vagrant/source
    server_alias: "{{ domain }}"
  - name: 01-phpMyAdmin
    server_name: db.{{ domain }}
    document_root: "{{ phpmyadmin_dest }}"
    options:
      - "-Indexes"
      - "+FollowSymLinks"
    allow_override: All
    require:
      - type: ip
        value: 192.168.33
  - name: 02-MailCatcher
    server_name: mail.{{ domain }}
    proxy_pass:
      - from: /
        to: "http://localhost:{{ mailcatcher_web_port }}/"
    proxy_pass_reverse:
      - from: /
        to: "http://localhost:{{ mailcatcher_web_port }}/"

apache_cfg:
  enable_sendfile: no

apache_module_lua: no
apache_module_dav:
  dav: no
  dav_fs: no
  dav_lock: no
apache_module_lbmethod:
  bybusyness: no
  byrequests: no
  bytraffic: no
  heartbeat: no
apache_module_proxy:
  ajp: no
  balancer: no
  ftp: no

# mailcatcher_web_ip: 0.0.0.0
